[2025-06-18T13:50:43.067+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T13:50:43.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:47:33.602311+00:00 [queued]>
[2025-06-18T13:50:43.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:47:33.602311+00:00 [queued]>
[2025-06-18T13:50:43.103+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-06-18T13:50:43.117+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_stacked> on 2025-06-18 13:47:33.602311+00:00
[2025-06-18T13:50:43.130+0000] {standard_task_runner.py:63} INFO - Started process 9450 to run task
[2025-06-18T13:50:43.133+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'train_stacked', 'manual__2025-06-18T13:47:33.602311+00:00', '--job-id', '826', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpa7l_id6u']
[2025-06-18T13:50:43.138+0000] {standard_task_runner.py:91} INFO - Job 826: Subtask train_stacked
[2025-06-18T13:50:43.184+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:47:33.602311+00:00 [running]> on host 9c4806d77c92
[2025-06-18T13:50:43.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='train_stacked' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T13:47:33.602311+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T13:47:33.602311+00:00'
[2025-06-18T13:50:43.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T13:50:43.303+0000] {model_steps.py:897} ERROR - Error in train_stacked_model: invalid load key, 'f'.
[2025-06-18T13:50:43.303+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T13:50:43.303+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/model_steps.py", line 853, in train_stacked_model
    selected_data = pickle.load(f)
                    ^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'f'.
[2025-06-18T13:50:43.314+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting_modular, task_id=train_stacked, run_id=manual__2025-06-18T13:47:33.602311+00:00, execution_date=20250618T134733, start_date=20250618T135043, end_date=20250618T135043
[2025-06-18T13:50:43.323+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 826 for task train_stacked (invalid load key, 'f'.; 9450)
[2025-06-18T13:50:43.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T13:50:43.361+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T13:50:43.363+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
