[2025-06-18T17:19:07.274+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:19:07.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting.fetch_kse100 manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:19:07.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting.fetch_kse100 manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:19:07.315+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2025-06-18T17:19:07.329+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_kse100> on 2025-06-18 17:15:18.237055+00:00
[2025-06-18T17:19:07.335+0000] {standard_task_runner.py:63} INFO - Started process 4537 to run task
[2025-06-18T17:19:07.338+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting', 'fetch_kse100', 'manual__2025-06-18T17:15:18.237055+00:00', '--job-id', '1020', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpptl7art0']
[2025-06-18T17:19:07.340+0000] {standard_task_runner.py:91} INFO - Job 1020: Subtask fetch_kse100
[2025-06-18T17:19:07.383+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting.fetch_kse100 manual__2025-06-18T17:15:18.237055+00:00 [running]> on host 57c57e92cb28
[2025-06-18T17:19:07.464+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting' AIRFLOW_CTX_TASK_ID='fetch_kse100' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T17:15:18.237055+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T17:15:18.237055+00:00'
[2025-06-18T17:19:07.466+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T17:19:07.480+0000] {ingest.py:65} INFO - Fetching ^KSE from Yahoo Finance...
[2025-06-18T17:19:22.564+0000] {multi.py:184} ERROR - 
1 Failed download:
[2025-06-18T17:19:22.565+0000] {multi.py:197} ERROR - ['^KSE']: Timeout('Failed to perform, curl: (28) Operation timed out after 10002 milliseconds with 142356 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[2025-06-18T17:19:22.577+0000] {ingest.py:112} ERROR - Error fetching ^KSE: No data downloaded for ticker '^KSE'
[2025-06-18T17:19:22.577+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T17:19:22.581+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/ingest.py", line 83, in fetch_yahoo_finance
    raise ValueError(f"No data downloaded for ticker '{ticker}'")
ValueError: No data downloaded for ticker '^KSE'
[2025-06-18T17:19:22.595+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting, task_id=fetch_kse100, run_id=manual__2025-06-18T17:15:18.237055+00:00, execution_date=20250618T171518, start_date=20250618T171907, end_date=20250618T171922
[2025-06-18T17:19:22.607+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1020 for task fetch_kse100 (No data downloaded for ticker '^KSE'; 4537)
[2025-06-18T17:19:22.651+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T17:19:22.672+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:19:22.674+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
