[2025-06-18T11:58:50.079+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T11:58:50.106+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T11:38:44.716652+00:00 [queued]>
[2025-06-18T11:58:50.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T11:38:44.716652+00:00 [queued]>
[2025-06-18T11:58:50.115+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-06-18T11:58:50.129+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): evaluate_lasso> on 2025-06-18 11:38:44.716652+00:00
[2025-06-18T11:58:50.135+0000] {standard_task_runner.py:63} INFO - Started process 4219 to run task
[2025-06-18T11:58:50.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'evaluate_lasso', 'manual__2025-06-18T11:38:44.716652+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmp22w0xh5l']
[2025-06-18T11:58:50.140+0000] {standard_task_runner.py:91} INFO - Job 654: Subtask evaluate_lasso
[2025-06-18T11:58:50.181+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.evaluate_lasso manual__2025-06-18T11:38:44.716652+00:00 [running]> on host 9c4806d77c92
[2025-06-18T11:58:50.275+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='evaluate_lasso' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T11:38:44.716652+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T11:38:44.716652+00:00'
[2025-06-18T11:58:50.276+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T11:58:50.287+0000] {logging_mixin.py:188} INFO - Loading Lasso model from /opt/***/data/models/lasso_model.pkl
[2025-06-18T11:58:50.288+0000] {logging_mixin.py:188} INFO - Loading selected features from /opt/***/data/models/selected_features.csv
[2025-06-18T11:58:50.288+0000] {logging_mixin.py:188} INFO - Loading train/test data from /opt/***/data/models/train_test_data.csv
[2025-06-18T11:58:50.294+0000] {logging_mixin.py:188} INFO - Error in evaluate_lasso: invalid load key, 'f'.
[2025-06-18T11:58:50.295+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T11:58:50.295+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/model_steps.py", line 934, in evaluate_lasso
    selected_data = pickle.load(f)
                    ^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'f'.
[2025-06-18T11:58:50.308+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=usdpkr_forecasting_modular, task_id=evaluate_lasso, run_id=manual__2025-06-18T11:38:44.716652+00:00, execution_date=20250618T113844, start_date=20250618T115850, end_date=20250618T115850
[2025-06-18T11:58:50.317+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 654 for task evaluate_lasso (invalid load key, 'f'.; 4219)
[2025-06-18T11:58:50.351+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T11:58:50.366+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T11:58:50.368+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
